name: markovmodels
dependencies:
  - python >= 3.11
  - conda-forge::sundials
  - numpy
  - matplotlib
  - pandas
  - sympy
  - texlive-core
  - scikit-build
  - bash
  - regex
  - cmake
  - conda-forge::sundials
  - conda-forge::graphviz
  - conda-forge::pygraphviz
  - pip:
      - .
