name: markovmodels
dependencies:
  - python >= 3.9
  - conda-forge::sundials
  - bokeh=2.4.2
  - numpy
  - matplotlib
  - pandas
  - sympy
  - graphviz
  - texlive-core
  - scikit-build
  - bash
  - regex
  - cmake
  - pip:
      - .
      - ./syncropatch_export
  - conda-forge::sundials
  - conda-forge::graphviz
